Fixed #56: Support upgrade.

diff --git a/bin/housemd b/bin/housemd
--- a/bin/housemd
+++ b/bin/housemd
@@ -4,6 +4,17 @@ then
     echo "Please set JAVA_HOME to JDK 6+!"
     exit 1
 else
+    if [ "$1" = "upgrade" ];
+    then
+        curl -Lk https://raw.github.com/zhongl/HouseMD/master/bin/install | bash || {
+            echo "Upgrade failed, please try again." ;
+            exit 1 ;
+        }
+
+        echo "Upgrade successful!" ;
+        exit 0 ;
+    fi
+
     ROOT=`dirname  "$0"`
 
     if [ -f $JAVA_HOME/lib/tools.jar ];
