Fixed #42: Validate download jar by md5 in install script.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,5 +1,19 @@
 #! /bin/bash
 
-curl -Lk https://github.com/downloads/zhongl/HouseMD/housemd-assembly-0.2.3.jar > housemd.jar
+CHECKSUM="checksum"
+curl -Lk https://api.github.com/repos/zhongl/HouseMD/downloads | grep -E "[0-9a-f]+\s+[^ \"]+" -o > $CHECKSUM
+
+JAR_NAME=`cat $CHECKSUM | grep -E housemd.+ -o`
+
+curl -Lk https://github.com/downloads/zhongl/HouseMD/$JAR_NAME > $JAR_NAME
+
+shasum -c $CHECKSUM || {
+    rm -rf $JAR_NAME $CHECKSUM ;
+    echo "Download failed, please try again!";
+    exit 1;
+}
+
+mv $JAR_NAME housemd.jar
+rm -rf $CHECKSUM
 curl -Lk https://raw.github.com/zhongl/HouseMD/master/bin/housemd > housemd
 chmod u+x housemd
